### PR TITLE
rust-client: Update to proto changes

### PR DESCRIPTION
**Pull request by elenaf9**
- Updates the rust-client to `libp2pv0.49.0`

- Fixes issue #37.
Unfortunately for none of the new properties we have all of the required information exposed in rust-libp2p. Thus we right now just leave them empty. The only thing we might be able to add is the `network_information`. However, that would require some more work and I am not sure if it's high priority. @dennis-tra does the `network_information`  have major relevance in your analysis?

### CODE REVIEW

**Comment by elenaf9** [comment]
CI is failing since rust-libp2p now requires `protoc` to be installed. I am not very familiar with how to properly add the protoc installation to the CI, @mxinden @thomaseizinger could you help here?

**Comment by dennis-tra** [comment]
> does the `network_information` have major relevance in your analysis?

It's fine if the rust-client won't submit it. All of the information is optional and would just be beneficial 👍

---

Regarding protoc, we could merge this PR and then in a second one fix CI.

**Comment by thomaseizinger** [comment]
> CI is failing since rust-libp2p now requires `protoc` to be installed. I am not very familiar with how to properly add the protoc installation to the CI, @mxinden @thomaseizinger could you help here?

Does copy-pasting the action we use on `rust-libp2p` not do the trick?

**Comment by elenaf9** [comment]
> > CI is failing since rust-libp2p now requires `protoc` to be installed. I am not very familiar with how to properly add the protoc installation to the CI, @mxinden @thomaseizinger could you help here?
> 
> Does copy-pasting the action we use on `rust-libp2p` not do the trick?

I wasn't sure whether it's enough to just copy that one line but apparently it is :smile:

**Pull request merged**
